# Generated by Django 4.2.11 on 2024-04-05 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Fotoğraf"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="content",
            field=models.TextField(verbose_name="İçerik"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Satıcı",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Ürün Adı"),
        ),
    ]
