# Generated by Django 4.2.11 on 2024-04-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["-comment_date"]},
        ),
        migrations.AlterModelOptions(
            name="product", options={"ordering": ["-created_date"]},
        ),
    ]
